// <auto-generated />
namespace Sklep_MJ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetabelizamowienia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetabelizamowienia));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251336328_update tabeli zamowienia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
