// <auto-generated />
namespace Sklep_MJ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removetestfieldfromcourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removetestfieldfromcourse));
        
        string IMigrationMetadata.Id
        {
            get { return "201810030914247_remove test field from course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
